services:
  backend:
    build:
      context: Backend
      dockerfile: Dockerfile
    container_name: gitbounty-backend
    ports:
      - "8081:8081"
    volumes:
      - gitbounty-repositories:/app/repositories
    environment:
      - SPRING_APPLICATION_NAME=Backend
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gitbounty
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/gitbounty
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev_password
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=root_password
      - GIT_REPOSITORIES_ROOT=/app/repositories
      - KEYCLOAK_CLIENT_ID=gitbounty-backend
      - KEYCLOAK_CLIENT_SECRET=gitbounty-backend-secret
    develop:
      watch:
        - path: Backend/src
          action: rebuild
    depends_on:
      mysql: { condition: service_healthy }
      keycloak: { condition: service_started }
    networks:
      - gitbounty-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: gitbounty-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gitbounty
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 5s
    networks:
      - gitbounty-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: gitbounty-keycloak
    command: ["start-dev", "--db=mysql", "--import-realm"]
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=keycloak_password
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gitbounty-network

  nginx:
    build:
      context: .
      dockerfile: Frontend/gitbounty/Dockerfile
    image: nginx:alpine
    container_name: gitbounty-proxy
    ports:
      - "80:80"   # Handles the HTTP connection to force a redirect
      - "443:443" # Opens public HTTPS secure line
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    develop:
      watch:
        - path: ./nginx.conf
          action: rebuild
        - path: ./Frontend/gitbounty
          target: /usr/share/nginx/html
          action: sync
    depends_on:
      backend:
          condition: service_healthy
    networks:
        - gitbounty-network
volumes:
  mysql-data:
  gitbounty-repositories:

networks:
  gitbounty-network: