server.port=${SERVER_PORT:8081}
spring.docker.compose.enabled=false
# App Paths
git.repositories-root=${GIT_REPOSITORIES_ROOT:repositories}
# Proxy Support
server.forward-headers-strategy=FRAMEWORK
# Route all unmatched requests through GlobalExceptionHandler instead of BasicErrorController
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
# Swagger UI
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}
springdoc.swagger-ui.oauth.clientId=${SWAGGER_OAUTH_CLIENT_ID:gitbounty-frontend}
springdoc.swagger-ui.url=/v3/api-docs
# This allows Swagger to know the base URL of your API
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true