# App Config
spring.application.name=gitbounty-backend
server.port=${SERVER_PORT:8081}

# Database (Using environment variables provided by Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

# Security & Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

# Flyway
spring.flyway.enabled=true
spring.flyway.user=${FLYWAY_USER}
spring.flyway.password=${FLYWAY_PASSWORD}
spring.flyway.default-schema=${FLYWAY_SCHEMA:gitbounty}

# App Paths
git.repositories-root=${GIT_REPOSITORIES_ROOT:/home/gitbounty/repositories}

# Swagger UI
springdoc.api-docs.enabled=${SWAGGER_ENABLED:false}
springdoc.swagger-ui.oauth.clientId=gitbounty-frontend
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.realm=gitbounty
